FORMAT: 1A
HOST: http://yourITASserver:4730/
VERSION: 1.02

# ITAS Client Services Test

## Disclaimer

**** Warning: at this point, ITAS API does not support asynchronus or multithreading calls for POST, PUT and PATCH requests. Async or multithreading requests could result in various Error messages, or even a corruption of data in extreme cases and are therefore not supported. ****
<br />
<br />
<strong>Release notes</strong> (XX<sup>rd</sup> August 2018)

## New Endpoints

<ul>
<li>None</li>
</ul>

## Updated Endpoints

<ul>
    <li>None</li>
    
</ul>
<chandiv>** ends ** </div>

## AccessToken [/AT]
Model Header containing AccessToken

+ Model
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

# Group Valuation-Physical
Data endpoints for Trade Valuation

## Physical Trade Valuation Request Information [/Valuation/Physical/TradeValuationInfo/{RequestId}]
`GET` Information relating to the request of Physical Trade Valuation
### Read Physical Trade Valuation Request Information  [GET]
 
<b>Response Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|TradingEntityId|Trading Entity ID|`array`||||
|ContractType|Contract Type|`array`|||`P` or `S`|
|ContractStatus|Contract Status|`array`|||`O`, `C` or `Q`|
|ContractApproved|Contract Approved|`boolean`||||
|CounterpartyCode|Counterparty Code|`array`||||
|CommodityCodePart1|Commodity Code|`array`||||
|CommodityCodePart2|Commodity Origin|`array`||||
|CommodityCodePart3|Commodity Grade|`array`||||
|CommodityCodePart4|Commodity Code Section 4|`array`||||
|CommodityCodePart5|Commodity Code Section 5|`array`||||
|TraderCode|Trader Code|`array`||||
|DepartmentCode|Department Code|`array`||||
|PaymentTermCode|Payment Term Code|`array`||||
|ContractTermCode|Contract Term Code|`array`||||
|ContractTermPortCode|Contract Term Port Code|`array`||||
|ShipmentStatusCode|Shipment Status Code|`array`||||
|SingleCcyConVal|Single Currency Contract Value|`boolean`||||
|SingleCcyCosts|Single Currency Costs|`boolean`||||
|RateOfExchangeDate|Rate of Exchange Date|`number`||||
|TableExtension|Table Extension|`string`|9|||
|ValuationPeriod|Valuation Period|`array`||`Obsolete`||
|AppKey|Application Key|`string`||||
|IncludeFOPnLAndFOContractValuations|Include FO PnL and FO Contract Valuations|`boolean`||||


<b>Response Messages</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||
|RequestTime|Request Time|`datetime`||||
|RequestStatus|Request Status|`string`||||
|RequestCompleteTime|Request Complete Time|`datetime`||||

+ Parameters
    + RequestId (required, string, `a123a456-7891-23a4-a567-8a9a10aaa123`) ... Identify specific request ID.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (PhysicalTradeValRequest)
        + Response (200 SuccessResponse)
        + Messages (array [ResultsMessageComplete])

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 RequestIdResponse)




# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)

## 404 RequestIdResponse (object)
+ Response
    + Value: 404 Object not found (string)
+ Messages (array[404 ErrorMessageRequestIdMessage])

## 404 ErrorMessageRequestIdMessage (object)
+ Severity: Error (string)
+ Message: `API5067 - API : The value {RequestId} sent as the RequestId does not exist.` (string)


## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg (string)



## PhysicalTradeValRequest (object)
+ TradingEntityId: JT,DT (array[string])
+ ContractType: P,S (array[string])
+ ContractStatus: O,C (array[string])
+ ContractApproved: true (boolean)
+ CounterpartyCode: FOODSWAT.S,FOODCLOT.S (array[string])
+ CommodityCodePart1: CHE,SPR (array[string])
+ CommodityCodePart2: PASO,INCT (array[string])
+ CommodityCodePart3: 55,77 (array[string])
+ CommodityCodePart4: QWE,PTY (array[string])
+ CommodityCodePart5: RTY,PLE (array[string])
+ TraderCode: JS,AN (array[string])
+ DepartmentCode: NAD,OMP (array[string])
+ PaymentTermCode: INV30,INV40 (array[string])
+ ContractTermCode: DEL,INT (array[string])
+ ContractTermPortCode: LIV,LDN (array[string])
+ ShipmentStatusCode: D,IT (array[string])
+ SingleCcyConVal: true (boolean)
+ SingleCcyCosts: false (boolean)
+ RateOfExchangeDate: 20161028 (number)
+ TableExtension: `_20161032` (string)
+ ValuationPeriod: AUG16,SEP16 (array[string])
+ AppKey: ABC123 (string)
+ IncludeFOPnLAndFOContractValuations: false (boolean)



## ResultsMessageComplete (object)
+ RequestId: `a123a456-7891-23a4-a567-8a9a10aaa123` (string)
+ RequestTime: `2016-07-01T12:20:30Z` (string)
+ RequestStatus: Completed (string)
+ RequestCompleteTime: `2016-07-01T12:22:30Z` (string)

